[theme]
primaryColor = "#8E9AAF"                  # 莫兰迪蓝灰
backgroundColor = "#F4F5F7"              # 柔和暖浅灰背景
secondaryBackgroundColor = "#E2E4E9"     # 莫兰迪浅灰色
textColor = "#333D47"                    # 深灰蓝文字
font = "sans serif"
